name: SkyGens
version: '1.0'
main: org.kim.SkyGens.SkyGens
api-version: '1.21'
softdpend: [ 'Multiverse-Core' ]
commands:
  createisland:
  istp:
  getgen:
  sell:
  money:
  giveitems:
  test:
  skills:
